// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMAvjrzQOz0DS678r-Qs7RcXXoTJ0IVSo',
    appId: '1:467514559504:web:43dd404e1f3f69aa510e95',
    messagingSenderId: '467514559504',
    projectId: 'vesta-opensource',
    authDomain: 'vesta-opensource.firebaseapp.com',
    storageBucket: 'vesta-opensource.firebasestorage.app',
    measurementId: 'G-RSZM51TP00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa2sVMDvHCDlO8c5C09PVy1GsgJWDw8pg',
    appId: '1:467514559504:android:bd4667ed516b6858510e95',
    messagingSenderId: '467514559504',
    projectId: 'vesta-opensource',
    storageBucket: 'vesta-opensource.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIKCVCNPmv-IW43PjwUoni601KMBZ5-Mc',
    appId: '1:467514559504:ios:d53cb768113c822f510e95',
    messagingSenderId: '467514559504',
    projectId: 'vesta-opensource',
    storageBucket: 'vesta-opensource.firebasestorage.app',
    androidClientId: '467514559504-m6mekkati0tegen1nu0l1jo4n8ojclac.apps.googleusercontent.com',
    iosClientId: '467514559504-36eq09ng3d178i7rrm0n8f70iv52uriu.apps.googleusercontent.com',
    iosBundleId: 'com.example.vestaTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIKCVCNPmv-IW43PjwUoni601KMBZ5-Mc',
    appId: '1:467514559504:ios:d53cb768113c822f510e95',
    messagingSenderId: '467514559504',
    projectId: 'vesta-opensource',
    storageBucket: 'vesta-opensource.firebasestorage.app',
    androidClientId: '467514559504-m6mekkati0tegen1nu0l1jo4n8ojclac.apps.googleusercontent.com',
    iosClientId: '467514559504-36eq09ng3d178i7rrm0n8f70iv52uriu.apps.googleusercontent.com',
    iosBundleId: 'com.example.vestaTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMAvjrzQOz0DS678r-Qs7RcXXoTJ0IVSo',
    appId: '1:467514559504:web:b81e87f27b0157ce510e95',
    messagingSenderId: '467514559504',
    projectId: 'vesta-opensource',
    authDomain: 'vesta-opensource.firebaseapp.com',
    storageBucket: 'vesta-opensource.firebasestorage.app',
    measurementId: 'G-1ST7F8SVTN',
  );
}
